FORMAT: 1A
HOST: http://52.74.132.72:3002/users

# Promoted Users
Promoted Users is a simple API allowing Admin to promote any user other than Admin to Promoted/Fasttrack Moderation States.

# Group Users
Access to Users related promotion.

## Promote a User [/{user_id}/promoted]
### Promote a User whose id is passed as in uid variable [PUT]

+ Parameters
    + user_id (required, number, `256`)... User ID who need to be promoted
        
+   Response 200 (application/json)

    + Body
    
            {
                  "responseCode": 200,
                  "message": "PASS"
            }

    